language: php
php:
    - 5.4

before_script:
    - composer self-update
    - composer install --dev --prefer-dist
    - chmod +x bin/execute_tests_paratest.sh
    - "sh -e /etc/init.d/xvfb start"
    - "export DISPLAY=:99.0"
    - "wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar"
    - "java -jar selenium-server-standalone-2.41.0.jar > /dev/null &"
    - sleep 5

script:
    - export BROWSER=firefox
    - bin/execute_tests_paratest.sh